# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YWTestInputField' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YWTestInputField

  target 'YWTestInputFieldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YWTestInputFieldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'YWTopInputField', :path => '~/Documents/Github/YWTopInputField'
#pod 'YWTopInputField'
end
